// S0 — Source manifest + missing-source report.
// Records the authoritative inputs (paths, sha256, page counts) and documents
// source material that is known to have existed but is no longer recoverable.
import { execFileSync } from 'node:child_process'
import { existsSync, writeFileSync, statSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')

const SOURCES = [
  { volume: 'A', path: '/Users/williamgkirby/Downloads/MASTER A Van 1989-2003.pdf', expected_pages: 350 },
  { volume: 'B', path: '/Users/williamgkirby/Downloads/MASTER B 2003-2019.pdf', expected_pages: 373 },
]

const entries = []
for (const src of SOURCES) {
  if (!existsSync(src.path)) {
    console.error(`MISSING SOURCE: ${src.path}`)
    entries.push({ ...src, status: 'missing' })
    continue
  }
  console.log(`hashing ${src.path} ...`)
  const sha256 = execFileSync('shasum', ['-a', '256', src.path], { encoding: 'utf8' }).split(' ')[0]
  const pdfinfo = execFileSync('pdfinfo', [src.path], { encoding: 'utf8' })
  const pages = Number(pdfinfo.match(/^Pages:\s+(\d+)/m)?.[1])
  const rotation = Number(pdfinfo.match(/^Page rot:\s+(\d+)/m)?.[1] ?? 0)
  entries.push({
    volume: src.volume,
    path: src.path,
    bytes: statSync(src.path).size,
    sha256,
    pages,
    page_rotation_deg: rotation,
    pages_match_expected: pages === src.expected_pages,
    status: 'ok',
  })
}

writeFileSync(
  join(ROOT, 'pipeline/sources.json'),
  JSON.stringify({ generated_by: '00_manifest.mjs', sources: entries }, null, 2),
)

const missingReport = `# Missing-source report

Generated by \`pipeline/00_manifest.mjs\`.

## Available sources

${entries
  .map(
    (e) =>
      `- **Volume ${e.volume}** — \`${e.path}\` (${e.pages} PDF pages, ${(e.bytes / 1e6).toFixed(0)} MB, sha256 \`${e.sha256?.slice(0, 16)}…\`)`,
  )
  .join('\n')}

Each PDF page is a scanned *spread* (two physical diary pages). Both volumes
open with a handwritten index mapping diary page numbers to trip place names.

## Known-lost material (searched for, not recoverable)

A prior website build existed and was delivered via WeTransfer around
2026-04-02 (\`wetransfer_site_2026-04-02_1546 2/camping-diaries 2/\`). It has
been deleted from this machine. An exhaustive search (Spotlight, filesystem
walk, every zip/tar archive in ~/Downloads, Trash) on 2026-06-12 found **no
trace** of:

- \`route_audit.py\` (legacy route-audit script)
- \`data/data.json\` (legacy trip data)
- \`data/routes.json\` (legacy route definitions)
- \`data/routes_geo.json\` (legacy GeoJSON geometry)

Per the evidence hierarchy these would only have been comparison inputs
(lowest tier). Their absence does not reduce the authority of the rebuilt
data, which is extracted directly from the diary scans — but no
legacy-vs-rebuilt comparison is possible.

## Other absent material

- **No pre-existing OCR text.** \`~/ocr_script.py\` (a tesseract script) exists
  but never produced output; tesseract cannot read cursive handwriting anyway.
  All transcription in this pipeline is vision-LLM based.
- **No \`MASTER C\` or later volume.** The diaries end in 2019 per Volume B's
  cover. No third volume was found on this machine.
`
writeFileSync(join(ROOT, 'reports/missing_sources.md'), missingReport)
console.log('wrote pipeline/sources.json and reports/missing_sources.md')
for (const e of entries) console.log(`  vol ${e.volume}: ${e.pages} pages, rot=${e.page_rotation_deg}, ok=${e.pages_match_expected}`)
